title: The Moim (더모임 나를 만나는 공간) 
description: > # this means to ignore newlines until "baseurl:"
  '더모임 나를 만나는 공간' 은 그림심리, 음악심리, 컬러테라피, 적성검사를 통해서 나를 찾아가는 컨설팅 테마 카페입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "treemtwater.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: light # Or use dark

# Profile information
name: The Moim 
tagline: '더모임, 나를 만나는 공간' 
about-description: > # Add Discription
  그림심리, 음악심리, 컬러테라피, 적성검사를 통해서 나를 찾아가는 컨설팅 테마 카페 <br>
  Consulting Theme Cafe with art therapy. <br>
  <br>
  위치: 양재역 8번출구 도보 5분 <br>
  주소: 강남대로160-2 2층 the Moim <br>

pic: logo.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: grape_song2@naver.com # Add your Email address
phone: 010-4662-8710 # Add your Phone number
website: treemtwater.github.io # Add your website, do not add http://
#linkedin: # Add your Linkedin handle
#github: treemtwater # Add your Github handle
#twitter: '@artemsheludko_' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
